export type SentenceCard = {
  id: string;
  chinese: string;
  pinyin: string;
  english: string;
  focus: '使' | '让' | '叫' | '请';
  note: string;
  source: 'allset' | 'original';
};

export const sentences: SentenceCard[] = [
  {
    id: 'shi-speech',
    chinese: '他的演讲使听众们非常激动。',
    pinyin: 'Tā de yǎnjiǎng shǐ tīngzhòng men fēicháng jīdòng.',
    english: 'His speech made the audience very excited.',
    focus: '使',
    note: '使 introduces the people affected (听众们), followed by the result (非常激动).',
    source: 'allset',
  },
  {
    id: 'shi-crisis',
    chinese: '经济危机使很多公司倒闭了，也使很多人失去了工作。',
    pinyin: 'Jīngjì wēijī shǐ hěn duō gōngsī dǎobì le, yě shǐ hěn duō rén shīqù le gōngzuò.',
    english: 'The financial crisis caused many companies to close and many people to lose their jobs.',
    focus: '使',
    note: 'A formal cause-and-effect sentence. Repeating 使 creates a balanced written structure.',
    source: 'allset',
  },
  {
    id: 'rang-go',
    chinese: '你为什么不让我去？',
    pinyin: 'Nǐ wèishénme bù ràng wǒ qù?',
    english: "Why won't you let me go?",
    focus: '让',
    note: 'In conversation, context tells you whether 让 means “let” or “make.”',
    source: 'allset',
  },
  {
    id: 'rang-movie',
    chinese: '这部电影让人很感动。',
    pinyin: 'Zhè bù diànyǐng ràng rén hěn gǎndòng.',
    english: 'This movie really moves people.',
    focus: '让',
    note: '让 is the everyday spoken counterpart to formal 使 in this result pattern.',
    source: 'allset',
  },
  {
    id: 'rang-grandpa',
    chinese: '那个老人让我想到了我爷爷。',
    pinyin: 'Nàge lǎorén ràng wǒ xiǎngdào le wǒ yéye.',
    english: 'That old man made me think of my grandpa.',
    focus: '让',
    note: 'The result can be an action phrase such as 想到, not only an adjective.',
    source: 'allset',
  },
  {
    id: 'jiao-do',
    chinese: '他不听话，你叫我怎么办？',
    pinyin: 'Tā bù tīnghuà, nǐ jiào wǒ zěnmebàn?',
    english: "He won't listen. What would you have me do?",
    focus: '叫',
    note: '叫 can mean “have/tell someone to do” in an informal causative sentence.',
    source: 'allset',
  },
  {
    id: 'jiao-think',
    chinese: '他偷偷约别的女孩，你叫我怎么想？',
    pinyin: 'Tā tōutōu yuē bié de nǚhái, nǐ jiào wǒ zěnme xiǎng?',
    english: 'He secretly asked other girls out. What am I supposed to think?',
    focus: '叫',
    note: '你叫我怎么… is a useful spoken frame for “how do you expect me to…?”',
    source: 'allset',
  },
  {
    id: 'jiao-headache',
    chinese: '你儿子在学校的表现叫老师很头疼。',
    pinyin: 'Nǐ érzi zài xuéxiào de biǎoxiàn jiào lǎoshī hěn tóuténg.',
    english: "Your son's behavior at school gives the teacher quite a headache.",
    focus: '叫',
    note: 'Here 叫 marks an effect on the teacher rather than a direct command.',
    source: 'allset',
  },
  {
    id: 'qing-favor',
    chinese: '我想请你帮我一个忙。',
    pinyin: 'Wǒ xiǎng qǐng nǐ bāng wǒ yí ge máng.',
    english: 'I want to ask you to do me a favor.',
    focus: '请',
    note: '请 makes the request polite: ask + person + action.',
    source: 'allset',
  },
  {
    id: 'qing-dog',
    chinese: '能不能请你明天照顾一下我的狗？',
    pinyin: 'Néng bu néng qǐng nǐ míngtiān zhàogù yíxià wǒ de gǒu?',
    english: 'Could I ask you to look after my dog tomorrow?',
    focus: '请',
    note: '能不能 and 一下 soften the request even further.',
    source: 'allset',
  },
  {
    id: 'shi-rain',
    chinese: '连续的大雨使河水上涨了。',
    pinyin: 'Liánxù de dàyǔ shǐ héshuǐ shàngzhǎng le.',
    english: 'The continuous heavy rain caused the river to rise.',
    focus: '使',
    note: '使 works naturally in factual, written cause-and-effect statements.',
    source: 'original',
  },
  {
    id: 'shi-calm',
    chinese: '这段音乐使我慢慢平静下来。',
    pinyin: 'Zhè duàn yīnyuè shǐ wǒ mànmàn píngjìng xiàlái.',
    english: 'This piece of music gradually calmed me down.',
    focus: '使',
    note: '下来 shows the resulting transition into a calmer state.',
    source: 'original',
  },
  {
    id: 'shi-efficient',
    chinese: '新的流程使我们的工作更有效率。',
    pinyin: 'Xīn de liúchéng shǐ wǒmen de gōngzuò gèng yǒu xiàolǜ.',
    english: 'The new process made our work more efficient.',
    focus: '使',
    note: 'A common workplace pattern: change + 使 + affected thing + improvement.',
    source: 'original',
  },
  {
    id: 'shi-hard',
    chinese: '信息太多反而使决定变得更难。',
    pinyin: 'Xìnxī tài duō fǎn’ér shǐ juédìng biàn de gèng nán.',
    english: 'Too much information instead made the decision harder.',
    focus: '使',
    note: '反而 signals a result contrary to expectation; 变得 introduces the changed state.',
    source: 'original',
  },
  {
    id: 'rang-window',
    chinese: '请把窗户打开，让空气进来。',
    pinyin: 'Qǐng bǎ chuānghu dǎkāi, ràng kōngqì jìnlái.',
    english: 'Please open the window and let the air in.',
    focus: '让',
    note: 'Here 让 clearly means “allow,” because the air is permitted to enter.',
    source: 'original',
  },
  {
    id: 'rang-laugh',
    chinese: '他讲的故事让大家都笑了。',
    pinyin: 'Tā jiǎng de gùshi ràng dàjiā dōu xiào le.',
    english: 'The story he told made everyone laugh.',
    focus: '让',
    note: 'A natural spoken sentence with an action, 笑了, as the result.',
    source: 'original',
  },
  {
    id: 'jiao-wait',
    chinese: '老板叫我们在会议室等他。',
    pinyin: 'Lǎobǎn jiào wǒmen zài huìyìshì děng tā.',
    english: 'The boss told us to wait for him in the meeting room.',
    focus: '叫',
    note: '叫 often carries the sense of an instruction from one person to another.',
    source: 'original',
  },
  {
    id: 'qing-explain',
    chinese: '请老师再解释一遍这个语法点。',
    pinyin: 'Qǐng lǎoshī zài jiěshì yí biàn zhège yǔfǎ diǎn.',
    english: 'Ask the teacher to explain this grammar point once more.',
    focus: '请',
    note: '请 + person + action can either invite or politely ask the person to act.',
    source: 'original',
  },
];
